---
# tasks file for configure_vm
# - name: Register VM with Red Hat / Subscribe to the Employee SKU
#   redhat_subscription:
#     state: present
#     username: "{{ rhn_username }}"
#     password: "{{ rhn_password }}"
#     #force_register: yes
#     pool: 8a85f981568e999d01568ed222cd6712

- name: Get list of enabled repositories
  command: subscription-manager repos --list-enabled
  register: enabled_repos

# - name: Disable all repositories
#   #shell: /bin/bash -c subscription-manager repos --disable=*
#   command: subscription-manager repos --disable=rhel-7-server-rt-beta-rpms

# - name: Enable required repositories
#   shell: /bin/bash -c subscription-manager repos --enable={{ item }}
#   with_items:
#     "{{ rhn_repos }}"
