---
# tasks file for openshift-prep
- name: Create a 2048-bit SSH key for root user
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  when: inventory_hostname in groups['masters']

- name: Deploy ssh key to root at all nodes
  authorized_key:
    user: root
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

- name: Install docker
  yum:
    name: docker
    state: latest

- name: Customize /etc/sysconfig/docker-storage-setup
  copy:
    src: files/docker-storage-setup
    dest: /etc/sysconfig/docker-storage-setup

- name: Verify existence of /dev/docker-vg/docker-pool
  stat:
    path: /dev/docker-vg/docker-pool
  register: docker_vg_status

- name: Run docker-storage-setup
  command: /usr/bin/docker-storage-setup
  when: docker_vg_status.stat.islnk is not defined

- name: Start and enable docker
  service:
    name: docker
    state: started
    enabled: true

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - wget
    - git
    - net-tools
    - bind-utils
    - iptables-services
    - bridge-utils
    - bash-completion
    - kexec-tools
    - sos
    - psacct
    - atomic-openshift-docker-excluder
    - atomic-openshift-excluder

- name: Install OpenShift tools
  yum:
    name: atomic-openshift-utils
    state: latest
  when: inventory_hostname in groups['masters']
