---
# tasks file for openshift-prep
- name: Install required packages
  yum:
    name:
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - kexec-tools
      - sos
      - psacct
      - docker
      - ansible
      - openshift-ansible
      - docker
    state: latest

- name: Generate OpenShift inventory file
  template:
    src: hosts.3.11.allinone
    dest: /tmp/openshift.hosts
  delegate_to: localhost

- name: Ready openshift-ansible for fetch
  archive:
    path: /usr/share/ansible/openshift-ansible
    dest: /tmp/openshift-ansible.tgz

- name: Fetch correct version of openshift-ansible from master
  fetch:
    src: /tmp/openshift-ansible.tgz
    dest: /tmp/
    flat: yes

- name: Extract openshift-ansible.tgz
  unarchive:
    src: /tmp/openshift-ansible.tgz
    dest: /tmp/
  delegate_to: localhost

- name: partition the device
  parted:
    device: /dev/vdb
    number: 1
    size: 55GiB
    state: present

- name: Create a volume group on top of /dev/vdb
  lvg:
    vg: vg_ocp
    pvs: /dev/vdb

- name: Create a LVM LV on the device that uses the all space.
  lvol:
    vg: vg_ocp
    lv: lv_ocp
    size: 100%FREE
    state: present

- name: Ensure a filesystem is created on the device.
  filesystem:
    fstype: xfs
    dev: /dev/vg_ocp/lv_ocp

- name: Create the mount point
  file:
    path: /ocp_pvs
    owner: root
    group: root
    mode: 01744

- name: Mount the device.
  mount:
    name: /ocp_pvs
    src: /dev/mapper/vg_ocp-lv_ocp
    fstype: xfs
    opts: noatime,nodiratime
    state: mounted
